name: element_query
description: A polyfill for Element Query.
version: 0.0.1
author: Man Hoang <jolleekin@outlook.com>
homepage: https://github.com/jolleekin/element_query

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  browser: any
